//! Poseidon2 Solidity library generation.
//!
//! Generates a Solidity library implementing Poseidon2 hash for t=5
//! (4-ary Merkle tree nodes: hash_4(a, b, c, d)).
//!
//! **GUARDRAIL G5**: Round constants are derived identically to
//! genshi-core/src/crypto/poseidon2.rs, ensuring on-chain Merkle tree
//! updates produce the same roots as the circuit.

use ark_ff::{BigInteger, PrimeField};

/// Generate the Poseidon2 Solidity library with round constants baked in.
///
/// The generated library provides:
/// - `hash4(uint256 a, uint256 b, uint256 c, uint256 d) -> uint256`
///   for 4-ary Merkle tree node hashing.
pub fn generate_poseidon2_sol() -> String {
    // Generate round constants using the same function as genshi-core
    let rc = genshi_core::crypto::poseidon2::generate_round_constants(
        b"genshi_poseidon2_bn254_t5",
        5 * 8 + 56, // t=5: 5*RF + RP = 40 + 56 = 96
    );

    let mut rc_hex = Vec::new();
    for c in &rc {
        let bytes = c.into_bigint().to_bytes_be();
        let hex = bytes.iter().map(|b| format!("{b:02x}")).collect::<String>();
        rc_hex.push(format!("0x{hex}"));
    }

    // Build the round constants array
    let mut rc_lines = String::new();
    for (i, h) in rc_hex.iter().enumerate() {
        rc_lines.push_str(&format!("        RC[{i}] = {h};\n"));
    }

    format!(r#"// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title Poseidon2
/// @notice Poseidon2 hash over BN254 Fr for genshi Merkle trees.
/// @dev Generated by genshi-evm. Round constants match genshi-core exactly (G5).
///      State width t=5, full rounds=8, partial rounds=56.
///      S-box: x^5 using mulmod (cheap on EVM).
library Poseidon2 {{
    uint256 constant P = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;

    /// @notice Hash 4 field elements to 1 (4-ary Merkle tree node).
    /// @dev state = [a, b, c, d, 0] -> permute -> output state[0]
    function hash4(uint256 a, uint256 b, uint256 c, uint256 d) internal pure returns (uint256) {{
        uint256[5] memory s;
        s[0] = a; s[1] = b; s[2] = c; s[3] = d; s[4] = 0;

        // Load round constants
        uint256[{num_rc}] memory RC;
{rc_lines}
        uint256 rcIdx = 0;

        // 4 initial full rounds
        for (uint256 r = 0; r < 4; r++) {{
            // Add round constants
            for (uint256 j = 0; j < 5; j++) {{
                s[j] = addmod(s[j], RC[rcIdx], P);
                rcIdx++;
            }}
            // S-box on all elements: x^5
            for (uint256 j = 0; j < 5; j++) {{
                uint256 x2 = mulmod(s[j], s[j], P);
                uint256 x4 = mulmod(x2, x2, P);
                s[j] = mulmod(x4, s[j], P);
            }}
            // External linear layer: s[i] += sum
            uint256 sum = 0;
            for (uint256 j = 0; j < 5; j++) {{
                sum = addmod(sum, s[j], P);
            }}
            for (uint256 j = 0; j < 5; j++) {{
                s[j] = addmod(s[j], sum, P);
            }}
        }}

        // 56 partial rounds
        for (uint256 r = 0; r < 56; r++) {{
            // Add round constant to first element only
            s[0] = addmod(s[0], RC[rcIdx], P);
            rcIdx++;
            // S-box on first element only
            uint256 x2 = mulmod(s[0], s[0], P);
            uint256 x4 = mulmod(x2, x2, P);
            s[0] = mulmod(x4, s[0], P);
            // Internal linear layer for t=5 with diag=[1,1,2,3,4]
            uint256 isum = 0;
            for (uint256 j = 0; j < 5; j++) {{
                isum = addmod(isum, s[j], P);
            }}
            // s[0] = sum (diag[0]-1=0, so 0*s[0]+sum)
            // s[1] = sum
            // s[2] = s[2] + sum  (diag[2]-1=1)
            // s[3] = 2*s[3] + sum (diag[3]-1=2)
            // s[4] = 3*s[4] + sum (diag[4]-1=3)
            uint256 old2 = s[2];
            uint256 old3 = s[3];
            uint256 old4 = s[4];
            s[0] = isum;
            s[1] = isum;
            s[2] = addmod(old2, isum, P);
            s[3] = addmod(addmod(old3, old3, P), isum, P);
            s[4] = addmod(addmod(addmod(old4, old4, P), old4, P), isum, P);
        }}

        // 4 final full rounds
        for (uint256 r = 0; r < 4; r++) {{
            for (uint256 j = 0; j < 5; j++) {{
                s[j] = addmod(s[j], RC[rcIdx], P);
                rcIdx++;
            }}
            for (uint256 j = 0; j < 5; j++) {{
                uint256 fx2 = mulmod(s[j], s[j], P);
                uint256 fx4 = mulmod(fx2, fx2, P);
                s[j] = mulmod(fx4, s[j], P);
            }}
            uint256 fsum = 0;
            for (uint256 j = 0; j < 5; j++) {{
                fsum = addmod(fsum, s[j], P);
            }}
            for (uint256 j = 0; j < 5; j++) {{
                s[j] = addmod(s[j], fsum, P);
            }}
        }}

        return s[0];
    }}
}}
"#,
        num_rc = rc.len(),
        rc_lines = rc_lines,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_poseidon2_sol() {
        let sol = generate_poseidon2_sol();
        assert!(sol.contains("library Poseidon2"));
        assert!(sol.contains("function hash4"));
        assert!(sol.contains("RC[0]"));
        // Check we have enough round constants
        assert!(sol.contains("RC[95]")); // Last constant index for t=5
    }
}
