// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title ShieldedPool
/// @notice Shroud Network shielded pool contract using UltraHonk verification.
/// @dev Integrates with the generated ShroudVerifier and Poseidon2 library.
///
/// Components:
/// - UltraHonk verifier (generated from verification key by shroud-evm)
/// - 4-ary Poseidon2 Merkle tree (depth 10, 1,048,576 leaves)
/// - Nullifier mapping: mapping(bytes32 => bool)
/// - Root history: circular buffer of 100 recent valid roots (Guardrail G4)
///
/// Verification uses BN254 precompiles (Guardrail G8):
///   ecAdd (0x06), ecMul (0x07), ecPairing (0x08), modexp (0x05)

interface IShroudVerifier {
    function verify(bytes calldata proof, uint256[] calldata publicInputs) external view returns (bool);
}

contract ShieldedPool {
    // ================================================================
    // Constants
    // ================================================================

    uint256 constant MERKLE_DEPTH = 10;
    uint256 constant ROOT_HISTORY_SIZE = 100;

    // ================================================================
    // State
    // ================================================================

    /// The verifier contract (generated by shroud-evm).
    IShroudVerifier public immutable verifier;

    /// Next available leaf index in the Merkle tree.
    uint256 public nextLeafIndex;

    /// Merkle tree node storage: nodes[level][index] = hash.
    /// Level 0 = leaves, level MERKLE_DEPTH = root.
    mapping(uint256 => mapping(uint256 => uint256)) public nodes;

    /// Circular buffer of recent Merkle roots (Guardrail G4).
    uint256[ROOT_HISTORY_SIZE] public rootHistory;
    uint256 public rootHistoryIndex;

    /// Nullifier set: spent nullifiers can never be reused.
    mapping(bytes32 => bool) public nullifiers;

    // ================================================================
    // Events
    // ================================================================

    event Deposit(uint256 indexed commitment, uint256 leafIndex, uint256 newRoot);
    event Transfer(bytes32 indexed nullifier, uint256 newCommitment1, uint256 newCommitment2, uint256 newRoot);
    event Withdrawal(bytes32 indexed nullifier, uint256 amount, address recipient);

    // ================================================================
    // Constructor
    // ================================================================

    constructor(address _verifier) {
        verifier = IShroudVerifier(_verifier);
        // Initialize root history with the empty tree root
        rootHistory[0] = _computeCurrentRoot();
    }

    // ================================================================
    // Deposit: add a commitment to the Merkle tree
    // ================================================================

    /// @notice Deposit tokens into the shielded pool.
    /// @param commitment The note commitment to insert into the Merkle tree.
    function deposit(uint256 commitment) external payable {
        uint256 leafIdx = nextLeafIndex;
        require(leafIdx < 4 ** MERKLE_DEPTH, "Tree is full");

        // Insert leaf
        nodes[0][leafIdx] = commitment;
        nextLeafIndex = leafIdx + 1;

        // Update Merkle tree path from leaf to root
        _updatePath(leafIdx);

        // Record new root in history
        uint256 newRoot = _computeCurrentRoot();
        rootHistoryIndex = (rootHistoryIndex + 1) % ROOT_HISTORY_SIZE;
        rootHistory[rootHistoryIndex] = newRoot;

        emit Deposit(commitment, leafIdx, newRoot);
    }

    // ================================================================
    // Transfer: spend an input note, create two output notes
    // ================================================================

    /// @notice Execute a private transfer.
    /// @param proof The UltraHonk proof bytes.
    /// @param publicInputs [merkle_root, nullifier, output_commitment_1, output_commitment_2]
    function transfer(bytes calldata proof, uint256[] calldata publicInputs) external {
        require(publicInputs.length == 4, "Transfer requires 4 public inputs");

        uint256 root = publicInputs[0];
        bytes32 nullifier = bytes32(publicInputs[1]);
        uint256 comm1 = publicInputs[2];
        uint256 comm2 = publicInputs[3];

        // Check root is in history (Guardrail G4)
        require(_isKnownRoot(root), "Unknown Merkle root");

        // Check nullifier not already spent
        require(!nullifiers[nullifier], "Nullifier already spent");

        // Verify the proof
        require(verifier.verify(proof, publicInputs), "Invalid proof");

        // Mark nullifier as spent
        nullifiers[nullifier] = true;

        // Insert new commitments
        uint256 leafIdx1 = nextLeafIndex;
        nodes[0][leafIdx1] = comm1;
        nextLeafIndex++;
        _updatePath(leafIdx1);

        uint256 leafIdx2 = nextLeafIndex;
        nodes[0][leafIdx2] = comm2;
        nextLeafIndex++;
        _updatePath(leafIdx2);

        // Record new root
        uint256 newRoot = _computeCurrentRoot();
        rootHistoryIndex = (rootHistoryIndex + 1) % ROOT_HISTORY_SIZE;
        rootHistory[rootHistoryIndex] = newRoot;

        emit Transfer(nullifier, comm1, comm2, newRoot);
    }

    // ================================================================
    // Withdraw: exit the shielded pool
    // ================================================================

    /// @notice Withdraw tokens from the shielded pool.
    /// @param proof The UltraHonk proof bytes.
    /// @param publicInputs [merkle_root, nullifier, amount, recipient]
    function withdraw(bytes calldata proof, uint256[] calldata publicInputs) external {
        require(publicInputs.length == 4, "Withdraw requires 4 public inputs");

        uint256 root = publicInputs[0];
        bytes32 nullifier = bytes32(publicInputs[1]);
        uint256 amount = publicInputs[2];
        address recipient = address(uint160(publicInputs[3]));

        require(_isKnownRoot(root), "Unknown Merkle root");
        require(!nullifiers[nullifier], "Nullifier already spent");
        require(verifier.verify(proof, publicInputs), "Invalid proof");

        nullifiers[nullifier] = true;

        // Transfer tokens to recipient
        (bool ok,) = recipient.call{value: amount}("");
        require(ok, "Transfer failed");

        emit Withdrawal(nullifier, amount, recipient);
    }

    // ================================================================
    // Internal: Merkle tree operations
    // ================================================================

    /// @dev Check if a root is in the history buffer.
    function _isKnownRoot(uint256 root) internal view returns (bool) {
        for (uint256 i = 0; i < ROOT_HISTORY_SIZE; i++) {
            if (rootHistory[i] == root) return true;
        }
        return false;
    }

    /// @dev Update the Merkle path from a leaf to the root.
    function _updatePath(uint256 leafIdx) internal {
        uint256 idx = leafIdx;
        for (uint256 level = 0; level < MERKLE_DEPTH; level++) {
            uint256 parentIdx = idx / 4;
            uint256 childBase = parentIdx * 4;

            // Get all 4 children at this level
            uint256 c0 = nodes[level][childBase];
            uint256 c1 = nodes[level][childBase + 1];
            uint256 c2 = nodes[level][childBase + 2];
            uint256 c3 = nodes[level][childBase + 3];

            // Hash them with Poseidon2 to get parent
            // NOTE: In production, this calls the Poseidon2 library.
            // For now, use a placeholder hash (keccak256 mod P).
            uint256 parent = uint256(keccak256(abi.encodePacked(c0, c1, c2, c3)));
            parent = parent % 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;

            nodes[level + 1][parentIdx] = parent;
            idx = parentIdx;
        }
    }

    /// @dev Compute the current root (topmost node).
    function _computeCurrentRoot() internal view returns (uint256) {
        return nodes[MERKLE_DEPTH][0];
    }
}
